travis:
  secure:
    BINSTAR_TOKEN: f4nipoaCe8tKzj2yaptiVfIXkw49RxOCEFvB7TIkP1ZkGc282CveRm6MNcack59FCDw675CpRwEtg6SdLR4ho76I8pcuBGaeJRqy77Fj8rA2mhtXA64W9F+JtPeO86+ssqAX818GBFmQeeCX/4T5Hx5CGVNjT3qG8BVh3j3M5ZnxgxiswM4r8KDElbvKoNL2HtJIiWV4obJ1H8OICY3PoODBvFVK0ArfI9aQx3xj1UAV//LuFRy+L9dFfxcyMCRejYexbM97Xsjp1Bao28XoppVA2NeQb4WwHFeOUvECBNbdUNrCPABzJ0H9tj/ygp1JFXYcPe62GK56mcTnxiI3QqDAUF9Aw89RIGzTuvRMGwc89qsIExN+G0SkbntB8CXpiRpbSkkA3iJK3MJXIzJQIJMHZw3FkHyi/rKwFZxdxVsMUAjx/yy9JDOQHLbn+LGmPmszRJE3xKfWOWFXHPoYcPPdU/UFOk0JoQ+l/2aJcYTzwrSoVw+JNsDF0QSyq8eRNmnBib0jXYryoZ8/Gr2hbvQMcQ2Bmn7YoATPH7Fgs2eA7kNR81GfY75PoOJ6AN2ILl2n0CCe0DQNyHA2GO+Ut88CqEFDERy64jk7goHxB9TzYsbKoxIP0R0zDqF7MEPXK4KGDOoKO6enVSb65N7UsUC12Ut48JAm7CcsjELsPeU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
